spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      schema: classpath:/sql/session_tables.sql
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/sarafan
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/sarafan
    locations: classpath:/db/migration
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
        jdbc:
          fetch_size: 100
          batch_size: 100
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ---------------------------------
            client-secret: -----------------------------
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: openid, email, profile