spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/sarafan
    driver-class-name: org.postgresql.Driver
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/sarafan
    locations: classpath:/db/migration
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
        jdbc:
          fetch_size: 100
          batch_size: 100